"""Add username field to messages table

Revision ID: 48875a91c67e
Revises: 11f2f245c24c
Create Date: 2024-10-13 21:09:17.631797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48875a91c67e'
down_revision = '11f2f245c24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
